version: '3.8'
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: keycloak
        MYSQL_USER: keycloak
        MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    networks:
      - keycloak-network
    command: ["mysqld", "--bind-address=0.0.0.0"]
    volumes:
      - ./custom_sql:/docker-entrypoint-initdb.d   # ホストマシンのカスタムSQLディレクトリをMySQLコンテナ内の特定ディレクトリにマウント
  keycloak:
    image: quay.io/keycloak/keycloak:18.0.0
    depends_on:
      - mysql
    environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: hilitehilite
        KC_DB : mysql
        KC_DB_URL: jdbc:mysql://mysql:3306/keycloak
        KC_DB_URL_DATABASE: keycloak
        KC_DB_USERNAME: keycloak
        KC_DB_PASSWORD: password
    ports:
      - "8180:8180"
    command: start-dev --http-port 8180 --http-relative-path /auth --proxy=reencrypt
    networks:
      - keycloak-network

networks:
  keycloak-network:
    driver: bridge

#volumes:
#  mysql_data:  # Define the named volume
